sudo: required

language: python

services:
  - docker

before_install:
  - docker build -f ./Python/Dockerfile . --tag=tinyfish:latest
  - docker run -d -p 127.0.0.1:80:5000 tinyfish:latest 
  - docker ps -a

script:
  - curl -I 127.0.0.1
