FROM ruby:2.4.2-jessie

RUN mkdir /app

# Don't bog the container down with extra files
COPY ./.git/ ./Gem* ./docs/Gem* /app/

WORKDIR /app/docs/

RUN bundle install

ENTRYPOINT ["jekyll"]

EXPOSE 4000
